name: "Get & Cache Dependencies"
description: 'Get the dependencies (via yarn) and cache them.'
inputs:
  caching:
    description: "Whether to cache dependencies or not"
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache yarn dependencies
        if: inputs.caching == "true"
        uses: actions/cache@v3
        id: cache
        with:
          path: "**/node_modules"
          key: node-modules-${{hashFiles('**/yarn.lock')}}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: yarn
      shell: bash
