name: Using Containers
on: [workflow_dispatch, push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
